framework: mocha      # Mention the testing framework mocha, jest or jasmine.
preRun:
  command:
    - npm install
    - npm run build
postMerge:
  pattern:
    - "./test.js" # Glob pattern to path where tests that should run post-merge are written.
preMerge:
  pattern:
    - "./test.js" 
postRun:
  command:
    - node --version # Mention post-run steps here
version: 1.0